### ISSUE TITLE
Ansible-Galaxy installation is not the same as github

### ISSUE THREAD

**Issue by p-burke** [ngetchell/vscode#11]
Hi, I just installed this role using: `ansible-galaxy install ngetchell.vscode`, but it appears to download an old version. 

tasks/main.yml contains this:
```
---
# tasks file for vscode
- include: "os_{{ ansible_os_family }}.yml"

```
not, as is shown in gitlab:
```
---
# tasks file for vscode

- name: import os specific tasks
  include_tasks: "os_{{ ansible_os_family }}.yml"

- name: install extension
  shell: "code --install-extension {{ item }}"
  become: no
  register: result
  when: 
    - vscode_extension is defined
  loop: "{{ vscode_extension }}"
  changed_when: result.stdout is not search('is already installed.')

```
So it appears that for some reason the galaxy code is out of date.
